ktor {
  environment = dev

  deployment {
    port = 8080
    host = "0.0.0.0"
;     watch = [ classes ]
  }

  application {
    modules = [
      org.example.ApplicationKt.module
    ]
  }
}

db {
    url = "jdbc:postgresql://localhost:5432/ktor_bakery_db",
    driver = "org.postgresql.Driver",
    username = "ktor_user",
    password = "secret"
}

jwt {
  secret = "super-secret-key"
  issuer = "ktor-issuer"
  audience = "ktor-audience"
  realm = "ktor-sample"
  expiresIn = 2268000000
}